services:
  db:
    image: postgres:17-alpine
    container_name: predictify_db_container
    restart: always
    environment:
      POSTGRES_DB: predictify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      # Configuraci√≥n para mayor rendimiento
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5435:5432"
    volumes:
      - postgres_data_secure:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d predictify_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - predictify-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: predictify_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@predictifylabs.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - predictify-network

volumes:
  postgres_data_secure:
    driver: local

networks:
  predictify-network:
    driver: bridge
