services:
  db:
    image: postgres:16-alpine
    container_name: predictify_db_container
    restart: always
    environment:
      POSTGRES_DB: predictify_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"                # <--- CAMBIO CRÃTICO: Puerto externo 5435
    volumes:
      - postgres_data_secure:/var/lib/postgresql/data
    networks:
      - predictify-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: predictify_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@predictifylabs.com
      PGADMIN_DEFAULT_PASSWORD: secret
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - predictify-network

volumes:
  postgres_data_secure:

networks:
  predictify-network:
    driver: bridge
